<?php
    class MyFooter{
        function show_footer(){
            $obj =& get_instance();
            //$obj->load->helper('url');
            $cont = '<div id="footer" class="row-fluid">';
            $cont.= '<div class="row-fluid">';
            $cont.= '<div class="offset1 span2">';
            $cont.= '<ul class="noticias">';
            $cont.= '<li>Account Manager</li>';
            $cont.= '<li><a href="#">My Account</a></li>';
            $cont.= '<li><a href="#">My Renewals</a></li>';
            $cont.= '<li><a href="#">My Upgrades</a></li>';
            $cont.= '<li><a href="#">Account Settings</a></li>';
            $cont.= '<li><a href="#">Customer Information</a></li>';
            $cont.= '<li><a href="#">Order History</a></li>';
            $cont.= '</ul>';
            $cont.= '</div>';
            $cont.= '<div class="span2">';
            $cont.= '<ul class="noticias">';
            $cont.= '<li>Shopping</li>';
            $cont.= '<li><a href="#">Offer Disclaimers</a></li>';
            $cont.= '<li><a href="#">Domain Search</a></li>';
            $cont.= '<li><a href="#">Product Catalog</a></li>';
            $cont.= '<li><a href="#">Producr Advisor</a></li>';
            $cont.= '<li><a href="#">Gift Cards</a></li>';
            $cont.= '<li><a href="#">Mobile</a></li>';
            $cont.= '</ul>';
            $cont.= '</div>';
            $cont.= '<div class="span2">';
            $cont.= '<ul class="noticias">';
            $cont.= '<li>Resources</li>';
            $cont.= '<li><a href="#">Webmail</a></li>';
            $cont.= '<li><a href="#">WHOIS search</a></li>';
            $cont.= '<li><a href="#">ICANN Confirmation</a></li>';
            $cont.= '<li><a href="#">Affiliates</a></li>';
            $cont.= '<li><a href="#">Connect with Us</a></li>';
            $cont.= '<li><a href="#">Gadgets / Widgets</a></li>';
            $cont.= '</ul>';
            $cont.= '</div>';
            $cont.= '<div class="span2">';
            $cont.= '<ul class="noticias">';
            $cont.= '<li>Help and Support</li>';
            $cont.= '<li><a href="#">Support &amp; Sales</a></li>';
            $cont.= '<li><a href="#">Billing Support</a></li>';
            $cont.= '<li><a href="#">Email Our Support</a></li>';
            $cont.= '<li><a href="#">FAQ’s</a></li>';
            $cont.= '<li><a href="#">User’s Guides</a></li>';
            $cont.= '<li><a href="#">Report Spam</a></li>';
            $cont.= '</ul>';
            $cont.= '</div>';
            $cont.= '<div class="span2">';
            $cont.= '<ul>';
            $cont.= '<li>About</li>';
            $cont.= '<li><a href="#">Careers</a></li>';
            $cont.= '<li><a href="#">Security Center</a></li>';
            $cont.= '<li><a href="#">Company Info</a></li>';
            $cont.= '<li><a href="#">News Center</a></li>';
            $cont.= '<li><a href="#">Customer</a></li>';
            $cont.= '<li><a href="#">What’s New</a></li>';
            $cont.= '</ul>';
            $cont.= '</div>';
            $cont.= '</div>';
            $cont.= '<footer class="row-fluid">';
            $cont.= '<p>All rights reserved by <strong>Altivia<span>OT</span> © 2012.</strong>';
            $cont.= '<br>Visit our '.anchor('http://blog.altiviaot.com','<strong>blog</strong>').'</p>';
            $cont.= '</footer>';
            $cont.= '</div>';
            $cont.= '</div>';
            $cont.= '<body>';
            return $cont;
        }
    }
?>